### ISSUE TITLE
Viewing HTML

### ISSUE THREAD

**Issue by kensanata** [solderpunk/VF-1#20]
When `lynx --dump` is called on my system (currently a Windows machine), it doesn't detect the MIME type correctly. This will dump HTML to the screen:
```
lynx --dump /cygdrive/c/Users/asc/AppData/Local/Temp/tmps59jndr2
```
When using the correct extension for the temp file, it works:
```
cp /cygdrive/c/Users/asc/AppData/Local/Temp/tmps59jndr2 /cygdrive/c/Users/asc/AppData/Local/Temp/tmps59jndr2.html
lynx --dump /cygdrive/c/Users/asc/AppData/Local/Temp/tmps59jndr2.html
```
Using `w3m -T text/html %s` instead of `lynx --dump %s` as the viewer would work because we can pass along a MIME type. Alternatively, we need to make sure that the temp file has the right extension when looking at HTML items.

**Comment by solderpunk** [comment]
Aaah, so that's what's going on!  I had noticed that HTML output was not working correctly, but I wasn't sure why.  Thanks for looking into this.  I just skimmed the man page for lynx, and apparently if we add `-force_html` option it will format it properly regardless of the file extension.  I haven't tested this yet, though.

**Comment by solderpunk** [comment]
Yep, works as expected.
