### ISSUE TITLE
Tour Ranges

### ISSUE THREAD

**Issue by kensanata** [solderpunk/VF-1#22]
I often visit the phlogosphere, look at the top few entries and issue a command like `tour 1 2 3 4 5 6 7 8 9 10 11`. From then on, I just read using `t` and `n` and the occasional menu picking. This is cool. But for the laze ones among us, I think ` tour 1-11` would be even better. Or be fancy and allow `tour 1-3 5 8-11` .

**Comment by solderpunk** [comment]
Yes, I absolutely agree!  I had _exactly_ this in mind since the moment I came up with "tour", I was just too lazy to code it up at the time. :)  The dream is to be able to use a combination of "go" and "tour" in the `.vf1rc` file to automatically set up a tour for the 10 most recently updated phlogs!

**Comment by kensanata** [comment]
MR #23 should solve it.

**Comment by solderpunk** [comment]
Yup!  I did a little tweak so that if somebody accidentally puts two hyphens in one part it will notify them rather than silently ignoring that part, but otherwise looks good.  Thanks!
