### ISSUE TITLE
Add full support for the + type

### ISSUE THREAD

**Issue by jamestomasino** [solderpunk/VF-1#42]
Details on the + type here, including test content:

    gopher://gopher.black/1/explorations/redundanttype

The + type entries are being listed next to all the others, but do not function. They should probably be hidden from the user and activated only when an attempt at the primary DirEntity fails. When used, they should inherit the type of the parent DirEntity (the last non "+" type listed in the Gophermap).

See the link above for more details.

**Comment by solderpunk** [comment]
Sorry for the slow action, I'm planning to tackle this tomorrow!

Do you know of any existing implementations of support for this where the client caches redundant servers?  Maybe I've missed something, but this seems vaguely useless to me otherwise.  If the primary server happens to go down during the narrow window of time between when I load the menu that specifies the redundant server and when I follow the first link on that menu, sure, it might help.  Or if the primary server is always available but so heavily loaded all the time that 10% of requests fail due to resource exhaustion, it would be great (and this might have been a common scenario at the birth of gopher, but seems laughable today).  But if I've bookmarked someone's gopherhole at SDF, wake up one morning and try to follow that bookmark but SDF is down (probably the most common failure mode of modern gopher!), how does their having listed a redundant server help me at all unless my client remembers it from when I successfully loaded their stuff from SDF yesterday?

Very happy to implement this nevertheless, just trying to understand how it is supposed to work.

**Comment by jamestomasino** [comment]
Hey @solderpunk ,

It doesn't solve the problem of bookmarks, but it could still be useful in linking to other servers, generated phlog listings, etc. I'm not sure caching makes sense since it's not guaranteed that the gophermap claiming the links are redundant is correct. For instance, in the dystopian world of EVIL GOPHER someone could theoretically say there's a redundant floodgap and serve up sneaky fake content.

Is it vaguely useless, maybe mostly, but it's still in the core spec and something I think we could use creatively if there's client support.

Lynx and sacc have decided to go ahead and list the redundant servers below the original link, just with different decorations. Lynx will display (+++) in front of the redundant ones. I personally still prefer the invisible fall-back when primary server is unresponsive, but I don't think they felt it was worth the time investment for a feature that's so fringe

**Comment by solderpunk** [comment]
I think the invisible fall-back makes a lot of sense and is probably closest to what the spec writers had in mind.  If it's just an ordinary old link that the client indicates is a mirror in some subtle way, it seems pointless to have defined an item type for it.  You could just, well, use an ordinary old link and put "(mirror)" after the User_Name.  It's obvious that a different item type should be treated differently by the client, that's the entire point.

Reading the RFC, there is a strong vibe of "gopher is something underfunded university departments can host on a dusty old 386 they found under somebody's desk and still expect it to mostly work".  Those servers must have been pretty unreliable under heavy load, and some kind of basic failover or round robin load-sharing functionality is an obvious response to this.  It helps solve the problem while adding no additional cruft to the protocol.  They must have had something like this in mind.  Have you looked at what the UMN gopher client does with these types?

Re: EVIL GOPHER dystopia: an obvious defence mechanism is to only allow servers to declare redundant mirrors for their own content, or at least to treat third-party declarations differently.  If floodgap.com says that evilgopher.com is a redundant mirror, then trust that, but if evilgopher.com claims itself to be a mirror, perhaps do not.  Of course, all of this is moot because with plain text connections you can't deeply trust anything at all.

**Comment by solderpunk** [comment]
Well, I have *something* working now.  I hacked my local copy of VF-1 so that requests to "gopher.black" would either work normally or throw a fake network exception with 50:50 chances.  And after visiting `gopher.black/1/explorations/redundanttype` to pick up the redundant mirrors, the next time it hits one of these errors it randomly switches to one of the mirrors.  It seems to work pretty nicely!  I haven't tested it super extensively, feel free to try play around with it (since you can actually make gopher.black go up and down on demand) and let me know if you're happy with how it behaves.

I kind of really want to try round robin load-balancing now, but that's probably getting a bit carried away...

**Comment by jamestomasino** [comment]
UMN gopher client does it just like you expect and I prefer. The redundant servers are hidden and only used when the primary fails. The spec speaks to round robin load-balancing, but I haven't put gopher(1) to the test on that.

Great work on VF-1, though! Game-changer!!!
