### ISSUE TITLE
Markup

### ISSUE THREAD

**Issue by kensanata** [solderpunk/VF-1#55]
Could we render `**bold**` and `*italics*`? Using escape sequences, if enabled by an option? As a first step, I'd just use two [escape codes](http://xn--rpa.cc/irl/term.html):

```
echo -e "\x1b[1m this is bold \x1b[0m"
echo -e "\x1b[3m this is italic \x1b[0m"
```

What do you think?

**Comment by solderpunk** [comment]
VF-1 can't render - or not render - anything!  All it does is write the gopher response to a temp file and then hand that file off to an external program, e.g. `cat` (which won't render the above).  I like this system very much and don't want to change it, so VF-1 is not the place to address this.

*But* I like the idea a lot and had actually been thinking just in these past few days that once 1.0.0 is out I would like to start a small standalone project for a kind of "souped up `cat`" specifically to be used as a VF-1 handler for `plain/text` (and maybe `plain/html`, too?) which used escape codes and unicode characters (so that, e.g. the bullets in a MarkDown list could be not asterices but actual nice round bullets) to format things nicely.  This would be a great tool to explore the potential for upgrading the gopher user experience without making any protocol-level changes.

**Comment by kensanata** [comment]
Ah, i like that idea of using an external program very much. For maximum compatibility across platforms it would have to be a Python script, though, I’m guessing? Then again, how hard would it be to write a simple C program that does it.
Want me to look into it?

**Comment by kensanata** [comment]
Just saw [mdcat](https://github.com/lunaryorn/mdcat) exists.
