### ISSUE TITLE
Proper man page.

### ISSUE THREAD

**Issue by pacoesteban** [solderpunk/VF-1#56]
As discussed with @solderpunk the idea is to create a proper man page for `vf1` using [mdoc](http://mandoc.bsd.lv/mdoc/) that can be used downstream on any unix like operating system. 

The current Readme will be reduced a bit to show some examples and present the project.

I'll take this task, although it could take me a while to complete.

Any help from somebody with experience on this will be appreciated.

**Comment by kensanata** [comment]
I'm interested in helping out. :)

**Comment by kensanata** [comment]
#57 is my first attempt. I think we need to figure out how much of the README we want to move into the man page. As much as possible? I'd say yes, because as an ordinary user I usually don't know where the README files are located.

The README should contain all the information a developer needs: Installation.

The manual should contain all the information a user needs: Invocation, and the "Quick, informal tutorial-style introduction" in particular, but also Concepts, Handlers, Text encoding, RC file.

Agreed?

**Comment by kensanata** [comment]
Sadly I have no idea how to tell pypi where to install the man page.

**Comment by kensanata** [comment]
Oops, apparently this is an open issue. See [discussion](https://stackoverflow.com/questions/3657209/python-installing-man-pages-in-distutils-based-project).

**Comment by kensanata** [comment]
Actually, I went ahead and created a merge request that goes even further and moves most of the README to the man page. See #59.
